# Use a imagem base do SQL Server 2022
FROM mcr.microsoft.com/mssql/server:2019-latest

# Defina variáveis de ambiente necessárias para o SQL Server
# ENV SA_PASSWORD=
# ENV ACCEPT_EULA=Y
# ENV DB_PORT=${DB_PORT}

# Exponha a porta padrão do SQL Server
EXPOSE ${DB_PORT}

USER root
# mssql-tools adicionado para executar comandos SQL Server no helthcheck do docker-compose
RUN apt-get update && \
    if ! command -v sqlcmd &> /dev/null; then \
        apt-get install --no-install-recommends -y mssql-tools; \
    fi

RUN apt-get update && \
    if ! command -v dos2unix &> /dev/null; then \
        apt-get install --no-install-recommends -y dos2unix; \
    fi

# Copia o script SQL e o script de inicialização para o container
COPY init-db.sql /usr/src/app/init-db.sql
COPY startup.sh /usr/src/app/startup.sh

RUN dos2unix /usr/src/app/startup.sh

# Define o diretório de trabalho
WORKDIR /usr/src/app

# Torna o script de inicialização executável
RUN chmod +x startup.sh

# Defina o usuário para executar o SQL Server
USER mssql

# Copie arquivos de inicialização ou scripts, se necessário
# COPY init.sql /docker-entrypoint-initdb.d/

# Comando para iniciar o SQL Server
# CMD /opt/mssql/bin/sqlservr

# Comando para iniciar o SQL Server e executar o script de inicialização
# CMD ["./startup.sh"]
# Executar o script de inicialização
CMD ["/bin/bash", "/usr/src/app/startup.sh"]
